### ISSUE TITLE
Update to Go 1.5

### ISSUE THREAD

**Issue by jadengore** [wercker/box-golang#13]
Go 1.5 was just released, and Wercker's box should be updated to reflect that.

**Comment by fatih** [comment]
This is imho needed, place take care of this as there is no way to test our code against 1.5 right now.

**Comment by jadengore** [comment]
@fatih Wercker has a dedicated issue tracker repo, I'm going to repost this there sometime later today.

**Comment by fatih** [comment]
@jadengore sounds good :+1:

**Comment by hatchan** [comment]
It's probably best to keep it here. I'll take a look at it later tonight.
PR are welcome of course ^_^

**Comment by jadengore** [comment]
@hatchan Would love to PR later this evening, thanks :+1:

**Comment by hatchan** [comment]
Created the pr: #14

**Comment by jadengore** [comment]
It's updated! closing...
