### ISSUE TITLE
Support for Go 1.11

### ISSUE THREAD

**Issue by matcornic** [wercker/box-golang#19]
Hello,

Could you add support for Golang 1.11 ?
Some products now uses modules and can not be compiled anymore in this current version.

Thanks.

**Comment by hatchan** [comment]
It looks like you are still using the old stack. This has been deprecated for some time already, and support for it will be stopped soon. For more information regarding migrating see: https://devcenter.wercker.com/supplementary-information/faqs/migrating-to-workflows-from-classic/

**Comment by matcornic** [comment]
Oh ok, thanks 👌
